version: '3'

services:
  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=indice
    command: "uvicorn app.main:app --host=0.0.0.0 --port=8002 --reload --workers=1"

  mysql:
    image: mysql:latest
    container_name: meu-novo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: indice
    volumes:
      - my-new-db:/var/lib/mysql
      - ./sql-scripts/01-datatable.sql:/docker-entrypoint-initdb.d/01-datatable.sql
    ports:
      - "3306:3306"
    
volumes:
  my-new-db: